### ISSUE TITLE
Trash panda is failing!

### ISSUE THREAD

**Issue by dschwen** [hugary1995/raccoon#113]
## Bug Description

```
tutorials/surfing_boundary_problem.kumar_fracture: *** ERROR ***
tutorials/surfing_boundary_problem.kumar_fracture: /ramdisk/civet/build_0/raccoon/tutorials/surfing_boundary_problem/elasticity.i:204: missing required parameter 'Postprocessors/Jint/elastic_energy_name'
tutorials/surfing_boundary_problem.kumar_fracture: 	Doc String: "name of the elastic energy"
```

https://civet.inl.gov/job/913601/

## Steps to Reproduce
Look at Civet

## Impact
Makes stuff orange.

**Comment by dschwen** [comment]
Ok, it does not fail with moose devel or next. Why is it erroring on my PR then...?

**Comment by hugary1995** [comment]
A collaborator accidentally committed to master, and reverted immediately. It's a bit unfortunate that I have to enable "push to branch" for civet to automatically update my devel branch.
