### ISSUE TITLE
benshs do not run

### ISSUE THREAD

**Issue by selarem** [hugary1995/raccoon#137]
## Bug Description
I have compiled raccoon. run_test give ok for all of the tests. 
36 passed, 0 skipped, 0 pending, 0 failed
But I could not run the examples in benshmarks

## Steps to Reproduce
in raccoon/benchmarks/mode2_initial_damage
../../raccoon-opt -i fracture.i 
gives
*** ERROR ***
/opt/projects/raccoon/benchmarks/mode2_initial_damage/fracture.i:11: no variable 'l' found for substitution expression
/opt/projects/raccoon/benchmarks/mode2_initial_damage/fracture.i:67: no variable 'Gc' found for substitution expression
/opt/projects/raccoon/benchmarks/mode2_initial_damage/fracture.i:67: no variable 'l' found for substitution expression
/opt/projects/raccoon/benchmarks/mode2_initial_damage/fracture.i:67: no variable 'psic' found for substitution expression
/opt/projects/raccoon/benchmarks/mode2_initial_damage/fracture.i:80: no variable 'k' found for substitution expression

raccoon/benchmarks/mode2_initial_damage/fracture.i
## Impact
I would like to have this running to start using raccoon

**Comment by hugary1995** [comment]
I'm trying to remove all benchmarks. If you are looking for examples to get started, take a look in the tutorials folder.
