### ISSUE TITLE
nucleation model version 2022 implementation

### ISSUE THREAD

**Issue by BoZeng1997** [hugary1995/raccoon#147]
## Reason

Implement nucleation model 2022 version in paper
https://link.springer.com/article/10.1007/s10704-022-00653-z
## Design

One detail not mentioned in the paper, the compressive part of the external driving force should be a linear term of the phase field variable. The code will implement the linear version.

**Comment by lyyc199586** [comment]
will you just update the old `NucleationMicroForce` file?

**Comment by lyyc199586** [comment]
then should we also keep 2020 model as an option to choose? like we could choose to use 2020 or 2022 model as an option in this file?

**Comment by BoZeng1997** [comment]
yes. I have done it. I will commit it for review once I have better commented the code

**Comment by lyyc199586** [comment]
great!

**Comment by lyyc199586** [comment]
This should be closed as completed @TheGreatCid
