### ISSUE TITLE
Update some functions/names according to MOOSE

### ISSUE THREAD

**Issue by BoZeng1997** [hugary1995/raccoon#151]
just to update some object parameter names, function names so that they stop throwing warnings. Changes include but not restricted to:

1. The RankTwoTensor initializer in `PhaseFieldJIntegral`
2. The "f_name" to "property_name" in `CrackGeometricFunction` and `DegradationFunctionBase`
4. all test files using object mentioning 'f_name"

**Comment by lyyc199586** [comment]
I think we still have "f_name" elsewhere, maybe we should open an issue to just update them

**Comment by BoZeng1997** [comment]
> I think we still have "f_name" elsewhere, maybe we should open an issue to just update them

In fact, this is the one. I just did not update the Description.

**Comment by lyyc199586** [comment]
I mean where is the PR, did you already merged it?

**Comment by TheGreatCid** [comment]
@BoZeng1997 This seems to be fixed. Is that correct?

**Comment by BoZeng1997** [comment]
I think @lyyc199586  finished it.
