### ISSUE TITLE
Excutioner settings to solve elastodynamic explicitly 

### ISSUE THREAD

**Issue by lyyc199586** [hugary1995/raccoon#157]
## Bug Description

I am trying to solve elastodynamic part explicitly with Central difference time integrator, but getting  DIVERGED_PC_FAILED errors:
```
Time Step 1, time = 2e-05, dt = 2e-05
Linear solve did not converge due to DIVERGED_PC_FAILED iterations 0
               PC failed due to FACTOR_NUMERIC_ZEROPIVOT 
 Solve Did NOT Converge!
Aborting as solve did not converge
```

## Steps to Reproduce

For example, in tutorials for [mode1_brittle_fracture](https://hugary1995.github.io/raccoon/tutorials/02_mode1_brittle_fracture.html), I change the `Excutioner` block to
```
[Executioner]
  type = Transient
  start_time = 0
  end_time = 3.5e-3
  dt = 2e-5
  [TimeIntegrator]
    type = CentralDifference
  []
[]
```
and change the stress divergence and add inertiaforce, with some density
```
[Kernels]
  [solid_x]
    type = ADDynamicStressDivergenceTensors
    variable = disp_x
    component = 0
  []
  [solid_y]
    type = ADDynamicStressDivergenceTensors
    variable = disp_y
    component = 1
    save_in = fy
  []
  [inertia_x]
    type = ADInertialForce
    variable = disp_x
  []
  [inertia_y]
    type = ADInertialForce
    variable = disp_y
  []
[]
``` 

## Impact

I actually did the same thing for the elastodynamic solve in nano-pulsed simulation before and it works... I don't know why it cannot run now.

**Comment by hugary1995** [comment]
Can you reproduce this using a MOOSE test input file and open a bug report there?

**Comment by lyyc199586** [comment]
Now at https://github.com/idaholab/moose/issues/26653
