### ISSUE TITLE
How to install raccoon when you already have moose installed

### ISSUE THREAD

**Issue by ayush4424** [hugary1995/raccoon#161]
![image](https://github.com/hugary1995/raccoon/assets/135033854/a5f125ba-d6e9-44ff-8038-91593e8bf78e)
Do i need to start from step 2 only ?
On starting from step 1 in one of the devices i installed mini conda again and it removed the moose environment and upon entering conda create --name moose moose-libmesh moose-tools, the whole system hanged
On an other device i just skipped installing mini conda again and followed all steps but it shows error when i do step 3 i.e. make -j 6
Do i need to install Libtorch as well ? I found this keyword in one of the errors
Please help
Regards,
Ayush

**Comment by cunyizju** [comment]
If you have successfully installed MOOSE, you can just skip git submodule --init --recursive and optional commands.
It works well in my computer. Hope it helps.

Regards,
Bruce

**Comment by TheGreatCid** [comment]
Closing as this has been answered
