### ISSUE TITLE
LDLNucleation Example File Typo

### ISSUE THREAD

**Issue by irvin-rodriguez** [hugary1995/raccoon#180]
## Bug Description
There is a typo in https://github.com/hugary1995/raccoon/blob/0a90d5763b0c1241c0ff85a1a7bea3ce4623be41/tutorials/surfing_boundary_problem/fracture.i#L74C5-L74C28

The line should say: fracture_toughness = Gc_delta 

where Gc_delta  = Gc*delta

**Comment by lyyc199586** [comment]
that's my mistake, I forgot to push the updated example:

should be:

```python
[Kernels]
  [diff]
    type = ADPFFDiffusion
    variable = d
    fracture_toughness = Gc_delta
    regularization_length = l
    normalization_constant = c0
  []
  [source]
    type = ADPFFSource
    variable = d
    free_energy = psi
  []
  [nuc_force]
    type = ADCoefMatSource
    variable = d
    prop_names = 'ce'
    coefficient = 1
  []
[]

[Materials]
...
  [Gc_delta]
    type = ADParsedMaterial
    property_name = Gc_delta
    expression = 'Gc*delta'
    material_property_names = 'Gc delta'
  []
[]
```

I can update it later this day if you don't have time
