### ISSUE TITLE
Ductile fracture

### ISSUE THREAD

**Issue by hugary1995** [hugary1995/raccoon#38]
- [x] Extend the compressible Neo-Hookean model
- [x] Extend the hypoelastic models in tensor_mechanics
- [x] Support hardening laws: power-law
- [ ] Support hardening laws: exponential
- [x] Support hardening laws: temperature dependency

**Comment by TheGreatCid** [comment]
@hugary1995 This seems closeable, correct?

**Comment by hugary1995** [comment]
Sure
