### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by ehsanhaghighat** [hugary1995/raccoon#48]
## Bug Description
I get the following error while compiling raccoon: 

FixedPointTransient.C:28:18: error: no member named 'setInnerSolve' in 'TimeStepper'
  _time_stepper->setInnerSolve(&_fp_solve)

## Steps to Reproduce
- A fresh moose install following moose instructions. 
- cloning raccoon and building the app. 

## Impact

Can not compile raccoon.

**Comment by hugary1995** [comment]
Sorry for getting to this late. You shouldn't be seeing this error if you compile using the submodule moose in RACCOON.

**Comment by ehsanhaghighat** [comment]
Yes-I realized later that I should compile RACCOON directly, but forgot to close the issue. 
Thanks
